const esbuild = require('esbuild')
const fs = require('fs')

// First, build the ABsmartly SDK bundle for Zaraz (served from public/_zaraz/absmartly-sdk.js)
esbuild.buildSync({
  entryPoints: ['src/zaraz/static/absmartly-sdk-bundle.js'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  outfile: 'public/_zaraz/absmartly-sdk.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Generate the inline SDK bundle TypeScript file
const sdkBundlePath = 'public/_zaraz/absmartly-sdk.js'
const sdkBundleContent = fs.readFileSync(sdkBundlePath, 'utf-8')
const inlineFilePath = 'src/zaraz/static/sdk-bundle-inline.ts'

const inlineFileContent = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK as a string constant
 * Built from public/_zaraz/absmartly-sdk.js
 */

const sdkBundle = ${JSON.stringify(sdkBundleContent)}

export default sdkBundle
`

fs.writeFileSync(inlineFilePath, inlineFileContent)
console.log('Generated SDK bundle inline file')

// Build the main managed component
esbuild.buildSync({
  entryPoints: ['src/index.ts'],
  bundle: true,
  minify: true,
  platform: 'node',
  format: 'esm',
  target: ['esnext'],
  tsconfig: 'tsconfig.build.json',
  outfile: 'dist/index.js',
  external: ['node:*'],
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})
