const esbuild = require('esbuild')
const fs = require('fs')

// Build the full ABsmartly SDK bundle (with WebVitals)
esbuild.buildSync({
  entryPoints: ['src/bundles/absmartly-sdk-bundle.js'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  outfile: 'public/_zaraz/absmartly-sdk.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Build fast bundle (SDK only, plugins lazy-loaded)
esbuild.buildSync({
  entryPoints: ['src/bundles/absmartly-sdk-bundle-fast.js'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  treeShaking: true,
  outfile: 'dist/absmartly-sdk-fast.min.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Build lite bundle (SDK + DOMChanges, no WebVitals) for Worker mode
esbuild.buildSync({
  entryPoints: ['src/bundles/absmartly-sdk-bundle-lite.js'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  treeShaking: true,
  outfile: 'dist/absmartly-sdk-lite.min.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Log bundle sizes
const fullSize = fs.statSync('public/_zaraz/absmartly-sdk.js').size
const fastSize = fs.statSync('dist/absmartly-sdk-fast.min.js').size
const liteSize = fs.statSync('dist/absmartly-sdk-lite.min.js').size
console.log('Bundle sizes:')
console.log('  Full (all plugins): ' + (fullSize / 1024).toFixed(1) + 'KB')
console.log('  Lite (no WebVitals): ' + (liteSize / 1024).toFixed(1) + 'KB')
console.log('  Fast (lazy plugins): ' + (fastSize / 1024).toFixed(1) + 'KB')

// Generate inline SDK bundle TypeScript files
// Full bundle (with WebVitals) - used for Zaraz mode
const sdkBundlePath = 'public/_zaraz/absmartly-sdk.js'
const sdkBundleContent = fs.readFileSync(sdkBundlePath, 'utf-8')
const inlineFilePath = 'src/bundles/sdk-bundle-inline.ts'

const inlineFileContent = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK (FULL) as a string constant
 * Built from public/_zaraz/absmartly-sdk.js
 * Includes: SDK + DOMChangesPlugin + CookiePlugin + WebVitals
 */

const sdkBundle = ${JSON.stringify(sdkBundleContent)}

export default sdkBundle
`

fs.writeFileSync(inlineFilePath, inlineFileContent)
console.log('Generated SDK bundle inline file (full)')

// Lite bundle (no WebVitals) - used for WebCM inline mode
const liteBundlePath = 'dist/absmartly-sdk-lite.min.js'
const liteBundleContent = fs.readFileSync(liteBundlePath, 'utf-8')
const inlineLiteFilePath = 'src/bundles/sdk-bundle-inline-lite.ts'

const inlineLiteFileContent = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK (LITE) as a string constant
 * Built from dist/absmartly-sdk-lite.min.js
 * Includes: SDK + DOMChangesPlugin + CookiePlugin (NO WebVitals)
 * ~10KB smaller than full bundle for faster parsing
 */

const sdkBundleLite = ${JSON.stringify(liteBundleContent)}

export default sdkBundleLite
`

fs.writeFileSync(inlineLiteFilePath, inlineLiteFileContent)
console.log('Generated SDK bundle inline file (lite)')

// Build the main managed component
// Using platform: 'neutral' for Cloudflare Workers compatibility
// (Workers don't support Node.js-only APIs like JSDOM)
esbuild.buildSync({
  entryPoints: ['src/index.ts'],
  bundle: true,
  minify: true,
  platform: 'neutral',
  format: 'esm',
  target: ['esnext'],
  tsconfig: 'tsconfig.build.json',
  outfile: 'dist/index.js',
  mainFields: ['browser', 'module', 'main'],
  conditions: ['browser', 'import', 'default'],
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})
