const esbuild = require('esbuild')
const fs = require('fs')

console.log('Building ABsmartly SDK bundles from TypeScript sources...\n')

// Build Zaraz bundle (full with WebVitals)
// Use modern JavaScript - Blob URL approach handles template literals safely
esbuild.buildSync({
  entryPoints: ['src/sdk-sources/zaraz/bundle-full.ts'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  tsconfig: 'tsconfig.build.json',
  conditions: ['source', 'import', 'default'],
  outfile: 'src/bundles/absmartly-sdk-bundle-zaraz-full.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Build Zaraz bundle (lite without WebVitals)
esbuild.buildSync({
  entryPoints: ['src/sdk-sources/zaraz/bundle-lite.ts'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  tsconfig: 'tsconfig.build.json',
  conditions: ['source', 'import', 'default'],
  outfile: 'src/bundles/absmartly-sdk-bundle-zaraz-lite.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Build Worker bundle (full with WebVitals)
esbuild.buildSync({
  entryPoints: ['src/sdk-sources/worker/bundle-full.ts'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  tsconfig: 'tsconfig.build.json',
  conditions: ['source', 'import', 'default'],
  outfile: 'src/bundles/absmartly-sdk-bundle-worker-full.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Build Worker bundle (lite without WebVitals)
esbuild.buildSync({
  entryPoints: ['src/sdk-sources/worker/bundle-lite.ts'],
  bundle: true,
  minify: true,
  platform: 'browser',
  format: 'iife',
  tsconfig: 'tsconfig.build.json',
  conditions: ['source', 'import', 'default'],
  outfile: 'src/bundles/absmartly-sdk-bundle-worker-lite.js',
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Legacy: Copy Zaraz full bundle to public/_zaraz for backward compatibility
fs.copyFileSync(
  'src/bundles/absmartly-sdk-bundle-zaraz-full.js',
  'public/_zaraz/absmartly-sdk.js'
)

// Log bundle sizes
const zarazFullSize = fs.statSync('src/bundles/absmartly-sdk-bundle-zaraz-full.js').size
const zarazLiteSize = fs.statSync('src/bundles/absmartly-sdk-bundle-zaraz-lite.js').size
const workerFullSize = fs.statSync('src/bundles/absmartly-sdk-bundle-worker-full.js').size
const workerLiteSize = fs.statSync('src/bundles/absmartly-sdk-bundle-worker-lite.js').size

console.log('Bundle sizes:')
console.log('  Zaraz Full (with WebVitals):    ' + (zarazFullSize / 1024).toFixed(1) + 'KB')
console.log('  Zaraz Lite (no WebVitals):      ' + (zarazLiteSize / 1024).toFixed(1) + 'KB')
console.log('  Worker Full (with WebVitals):   ' + (workerFullSize / 1024).toFixed(1) + 'KB')
console.log('  Worker Lite (no WebVitals):     ' + (workerLiteSize / 1024).toFixed(1) + 'KB')
console.log()

const savings = zarazFullSize - zarazLiteSize
if (savings > 0) {
  console.log('✅ Tree-shaking working! Lite bundle is ' + (savings / 1024).toFixed(1) + 'KB smaller')
} else {
  console.log('⚠️  Warning: Tree-shaking may not be working optimally')
}
console.log()

// Generate inline SDK bundle TypeScript files for SDK injector
// Note: JSON.stringify handles escaping correctly - no additional escaping needed

// Zaraz Full - ES5 target eliminates template literals
const zarazFullContent = fs.readFileSync('src/bundles/absmartly-sdk-bundle-zaraz-full.js', 'utf-8')
const zarazFullInline = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK for Zaraz (FULL) as a string constant
 * Built from src/sdk-sources/zaraz/bundle-full.ts with ES5 target
 * Includes: SDK + DOMChangesPlugin + CookiePlugin + WebVitals + Zaraz integration
 */

const sdkBundleZarazFull = ${JSON.stringify(zarazFullContent)}

export default sdkBundleZarazFull
`
fs.writeFileSync('src/bundles/sdk-bundle-inline-zaraz-full.ts', zarazFullInline)

// Zaraz Lite - ES5 target eliminates template literals
const zarazLiteContent = fs.readFileSync('src/bundles/absmartly-sdk-bundle-zaraz-lite.js', 'utf-8')
const zarazLiteInline = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK for Zaraz (LITE) as a string constant
 * Built from src/sdk-sources/zaraz/bundle-lite.ts with ES5 target
 * Includes: SDK + DOMChangesPlugin + CookiePlugin + Zaraz integration (NO WebVitals)
 */

const sdkBundleZarazLite = ${JSON.stringify(zarazLiteContent)}

export default sdkBundleZarazLite
`
fs.writeFileSync('src/bundles/sdk-bundle-inline-zaraz-lite.ts', zarazLiteInline)

// Worker Full - ES5 target eliminates template literals
const workerFullContent = fs.readFileSync('src/bundles/absmartly-sdk-bundle-worker-full.js', 'utf-8')
const workerFullInline = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK for Worker (FULL) as a string constant
 * Built from src/sdk-sources/worker/bundle-full.ts with ES5 target
 * Includes: SDK + DOMChangesPlugin + CookiePlugin + WebVitals (NO Zaraz integration)
 */

const sdkBundleWorkerFull = ${JSON.stringify(workerFullContent)}

export default sdkBundleWorkerFull
`
fs.writeFileSync('src/bundles/sdk-bundle-inline-worker-full.ts', workerFullInline)

// Worker Lite - ES5 target eliminates template literals
const workerLiteContent = fs.readFileSync('src/bundles/absmartly-sdk-bundle-worker-lite.js', 'utf-8')
const workerLiteInline = `/**
 * This file is AUTO-GENERATED by esbuild.js
 * DO NOT EDIT MANUALLY
 *
 * Contains the bundled ABsmartly SDK for Worker (LITE) as a string constant
 * Built from src/sdk-sources/worker/bundle-lite.ts with ES5 target
 * Includes: SDK + DOMChangesPlugin + CookiePlugin (NO WebVitals, NO Zaraz integration)
 */

const sdkBundleWorkerLite = ${JSON.stringify(workerLiteContent)}

export default sdkBundleWorkerLite
`
fs.writeFileSync('src/bundles/sdk-bundle-inline-worker-lite.ts', workerLiteInline)

console.log('Generated inline bundle files:')
console.log('  ✅ sdk-bundle-inline-zaraz-full.ts')
console.log('  ✅ sdk-bundle-inline-zaraz-lite.ts')
console.log('  ✅ sdk-bundle-inline-worker-full.ts')
console.log('  ✅ sdk-bundle-inline-worker-lite.ts')
console.log()

// Build the main managed component
esbuild.buildSync({
  entryPoints: ['src/index.ts'],
  bundle: true,
  minify: true,
  platform: 'neutral',
  format: 'esm',
  target: ['esnext'],
  tsconfig: 'tsconfig.build.json',
  outfile: 'dist/index.js',
  mainFields: ['browser', 'module', 'main'],
  conditions: ['browser', 'import', 'default'],
  logOverride: {
    'equals-negative-zero': 'silent',
  },
})

// Copy SDK bundles to dist/ so they're available in the npm package
// This allows consumers using "local" strategy to serve them from their public directory
console.log('Copying SDK bundles to dist/...')
fs.copyFileSync('src/bundles/absmartly-sdk-bundle-zaraz-full.js', 'dist/absmartly-sdk-bundle-zaraz-full.js')
fs.copyFileSync('src/bundles/absmartly-sdk-bundle-zaraz-lite.js', 'dist/absmartly-sdk-bundle-zaraz-lite.js')
fs.copyFileSync('src/bundles/absmartly-sdk-bundle-worker-full.js', 'dist/absmartly-sdk-bundle-worker-full.js')
fs.copyFileSync('src/bundles/absmartly-sdk-bundle-worker-lite.js', 'dist/absmartly-sdk-bundle-worker-lite.js')
console.log('✅ SDK bundles copied to dist/')
console.log()

console.log('✅ Build completed successfully!')
